containers:
  default:
    docker: quay.io/kubernetes-ingress-controller/e2e:v06262019-ecce3fd7b

steps:
- label: Static Check
  timeout: 5m
  run:
  - build/static-check.sh
  env:
    PKG: Shopify/ingress

- label: Lua unit test
  timeout: 5m
  run:
  - build/test-lua.sh
  env:
    BUSTED_ARGS: -v --pattern=_test

- label: Go unit test
  timeout: 15m
  run:
  - mkdir -p $GOPATH/src/$PKG
  - cp -r /app/* $GOPATH/src/$PKG/
  - cd $GOPATH/src/$PKG && build/cover.sh
  env:
    PKG: k8s.io/ingress-nginx

- label: E2e test
  timeout: 45m
  run:
  - mkdir -p $GOPATH/src/$PKG
  - cp -r /app/* $GOPATH/src/$PKG/
  - sleep 9000
  - cd $GOPATH/src/$PKG && build/run-e2e-suite.sh
  env:
    PKG: "k8s.io/ingress-nginx"
    E2E_NODES: "10"
    SLOW_E2E_THRESHOLD: "50"
    K8S_VERSION: "v1.14.1"
    KUBERNETES_VERSION: "v1.13-latest"
    LOGGING_LEVEL: "4"
