containers:
  default:
    docker: quay.io/kubernetes-ingress-controller/e2e:v06262019-ecce3fd7b
  e2e:
    build:
      env:
        PIPA_PIPELINE_TEMPLATE: dockerfile
        PIPA_DOCKERFILE: test/e2e-image/Dockerfile
        PIPA_DOCKER_CACHE_FROM_BRANCH: "true"
        PIPA_TAG_BRANCH: "true"

steps:
- label: Static Check
  timeout: 5m
  run:
  - build/static-check.sh
  env:
    PKG: Shopify/ingress

- label: Lua unit test
  timeout: 5m
  run:
  - build/test-lua.sh
  env:
    BUSTED_ARGS: -v --pattern=_test

- label: Go unit test
  timeout: 15m
  run:
  - mkdir -p $GOPATH/src/$PKG
  - cp -r /app/* $GOPATH/src/$PKG/
  - cd $GOPATH/src/$PKG && build/cover.sh
  env:
    PKG: k8s.io/ingress-nginx

- label: E2e test
  timeout: 35m
  run:
  - build/shopify-e2e
  env:
    LOGGING_LEVEL: "4"
    KUBERNETES_VERSION: "v1.11-latest"
    PKG: "k8s.io/ingress-nginx"
    E2E_NODES: "10"
    SLOW_E2E_THRESHOLD: "50"
  container: e2e
