{{- if and (.Values.controller.ingressClassResource.enabled) (.Values.controller.ingressClassResource.extraNames) -}}
{{- range $v := .Values.controller.ingressClassResource.extraNames }}
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  labels:
    {{- include "ingress-nginx.labels" $ | nindent 4 }}
    app.kubernetes.io/component: controller
    {{- with $.Values.controller.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ $v | trim }}
spec:
  controller: {{ $.Values.controller.ingressClassResource.controllerValue }}
  {{ template "ingressClass.parameters" $ }}
{{- end }}
{{- end }}
