{{- if and .Values.controller.metrics.enabled .Values.controller.metrics.podMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "ingress-nginx.controller.fullname" . }}
{{- if .Values.controller.metrics.podMonitor.namespace }}
  namespace: {{ .Values.controller.metrics.podMonitor.namespace | quote }}
{{- end }}
  labels:
    {{- include "ingress-nginx.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
  {{- if .Values.controller.metrics.podMonitor.additionalLabels }}
    {{- toYaml .Values.controller.metrics.podMonitor.additionalLabels | nindent 4 }}
  {{- end }}
spec:
  podMetricsEndpoints:
    - port: metrics
      interval: {{ .Values.controller.metrics.podMonitor.scrapeInterval }}
    {{- if .Values.controller.metrics.podMonitor.honorLabels }}
      honorLabels: true
    {{- end }}
    {{- if .Values.controller.metrics.podMonitor.relabelings }}
      relabelings: {{ toYaml .Values.controller.metrics.podMonitor.relabelings | nindent 8 }}
    {{- end }}
    {{- if .Values.controller.metrics.podMonitor.metricRelabelings }}
      metricRelabelings: {{ toYaml .Values.controller.metrics.podMonitor.metricRelabelings | nindent 8 }}
    {{- end }}
{{- if .Values.controller.metrics.podMonitor.jobLabel }}
  jobLabel: {{ .Values.controller.metrics.podMonitor.jobLabel | quote }}
{{- end }}
{{- if .Values.controller.metrics.podMonitor.namespaceSelector }}
  namespaceSelector: {{ toYaml .Values.controller.metrics.podMonitor.namespaceSelector | nindent 4 }}
{{- else }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
{{- if .Values.controller.metrics.podMonitor.targetLabels }}
  targetLabels:
  {{- range .Values.controller.metrics.podMonitor.targetLabels }}
    - {{ . }}
  {{- end }}
{{- end }}
  selector:
    matchLabels:
      {{- include "ingress-nginx.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: controller
{{- end }}
