{{- if .Values.controller.ingressClassResource.enabled -}}
{{- range $index, $name := ( split "," .Values.controller.ingressClassResource.name ) }}
---
# We don't support namespaced ingressClass yet
# So a ClusterRole and a ClusterRoleBinding is required
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  labels:
    {{- include "ingress-nginx.labels" ( dict "customLabels" $.Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: controller
    {{- with $.Values.controller.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ $name | trim }}
{{- if and ($.Values.controller.ingressClassResource.default) (eq $index "_0") }}
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
{{- end }}
spec:
  controller: {{ $.Values.controller.ingressClassResource.controllerValue }}
  {{ template "ingressClass.parameters" $ }}
{{- end }}
{{- end }}