{{- if or (and .Values.controller.autoscaling.enabled (gt (.Values.controller.autoscaling.minReplicas | int) 1)) (gt (.Values.controller.replicaCount | int) 1) }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app: {{ template "ingress-nginx.name" . }}
    chart: {{ template "ingress-nginx.chart" . }}
    component: "{{ .Values.controller.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "ingress-nginx.controller.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "ingress-nginx.name" . }}
      release: {{ .Release.Name }}
      component: "{{ .Values.controller.name }}"
  minAvailable: {{ .Values.controller.minAvailable }}
{{- end }}
