{{- if gt (.Values.defaultBackend.replicaCount | int) 1 }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app: {{ template "ingress-nginx.name" . }}
    chart: {{ template "ingress-nginx.chart" . }}
    component: "{{ .Values.defaultBackend.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "ingress-nginx.defaultBackend.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "ingress-nginx.name" . }}
      release: {{ .Release.Name }}
      component: "{{ .Values.defaultBackend.name }}"
  minAvailable: {{ .Values.defaultBackend.minAvailable }}
{{- end }}
