annotations:
  artifacthub.io/changes: |-
    - "template pod affinity"
  artifacthub.io/prerelease: "false"
apiVersion: v2
appVersion: 1.10.1
description: Ingress controller for Kubernetes using NGINX as a reverse proxy and
  load balancer
home: https://github.com/kubernetes/ingress-nginx
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png
keywords:
  - ingress
  - nginx
kubeVersion: '>=1.21.0-0'
maintainers:
- name: Gacko
- name: rikatz
- name: strongjz
- name: tao12345666333
name: ingress-nginx
sources:
- https://github.com/kubernetes/ingress-nginx
version: 4.11.0
