package:
  name: lua-resty-ipmatcher
  version: {{ .LUA_RESTY_IPMATCHER_VERSION }}
  epoch: 0
  description: "High-performance match IP address for Nginx + Lua"
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      license: Apache-2.0 license
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
      - '@local /work/packages'
    packages:
      - alpine-baselayout-data
      - busybox
      - build-base
      - ssl_client
      - ca-certificates-bundle
      - luajit@local

  accounts:
    groups:
      - groupname: www-data
        gid: 10000
    users:
      - username: www-data
        uid: 10000

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/api7/lua-resty-ipmatcher/archive/{{ .LUA_RESTY_IPMATCHER_VERSION }}.tar.gz
      expected-sha256: {{ .LUA_RESTY_IPMATCHER_VERSION_SHA }}
      strip-components: 1
  - name: "Configure"
    run: |
      - name: "Configure"
    runs: |
      export LUAJIT_LIB=/usr/local/lib
      export LUA_LIB_DIR="$LUAJIT_LIB/lua"
      export LUAJIT_INC=/usr/local/include/luajit-2.1
      
      ln -s /usr/local/bin/luajit /usr/local/bin/lua
      ln -s "$LUAJIT_INC" /usr/local/include/lua
      
      export LUA_INCLUDE_DIR=/usr/local/include/luajit-2.1
      ln -s $LUA_INCLUDE_DIR /usr/include/lua5.1
      ls -lah /usr/local/lib
      
      #https://github.com/api7/lua-resty-ipmatcher/blob/master/Makefile#L22
      export INST_LUADIR="${{targets.destdir}}"
      
      make DESTDIR="${{targets.destdir}}" install
