package:
  name: lua-resty-upload
  version: {{ .LUA_RESTY_UPLOAD_VERSION }}
  epoch: 0
  description: "Streaming reader and parser for http file uploading based on ngx_lua cosocket"
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      license: BSD license
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
      - '@local /work/packages'
    packages:
      - alpine-baselayout-data
      - busybox
      - build-base
      - ssl_client
      - ca-certificates-bundle

  accounts:
    groups:
      - groupname: www-data
        gid: 10000
    users:
      - username: www-data
        uid: 10000

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/openresty/lua-resty-upload/archive/v{{ .LUA_RESTY_UPLOAD_VERSION }}.tar.gz
      expected-sha256: {{ .LUA_RESTY_UPLOAD_VERSION_SHA }}
      strip-components: 1
  - uses: autoconf/make-install
