package:
  name: luajit
  version: {{ .LUAJIT_VERSION }}
  epoch: 0
  description: "openresty/luajit2 - OpenResty's maintained branch of LuaJIT."
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      license: MIT license
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
    packages:
      - alpine-baselayout-data
      - busybox
      - build-base
      - ssl_client
      - ca-certificates-bundle

  accounts:
    groups:
      - groupname: www-data
        gid: 10000
    users:
      - username: www-data
        uid: 10000

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/openresty/luajit2/archive/v{{ .LUAJIT_VERSION }}.tar.gz
      expected-sha256: {{ .LUAJIT_VERSION_SHA }}
      strip-components: 1
  - name: 'Configure LUAJIT'
    with:
      LUAJIT_VERSION: {{ .LUAJIT_VERSION }}
    runs: |
      
      set -o errexit
      set -o nounset
      set -o pipefail
      
      echo "Arch: $(uname -m)"
      
      
      ARCH=$(uname -m)
      CORES=$(($(grep -c ^processor /proc/cpuinfo) - 1))
      
      mkdir -p ${{targets.destdir}}/etc/nginx
      
      export MAKEFLAGS=-j${CORES}
      export CTEST_BUILD_FLAGS=${MAKEFLAGS}
      export HUNTER_JOBS_NUMBER=${CORES}
      export HUNTER_USE_CACHE_SERVERS=true
      
      # Install luajit from openresty fork
      export LUAJIT_LIB=${{targets.destdir}}/usr/local/lib
      export LUA_LIB_DIR="$LUAJIT_LIB/lua"
      export LUAJIT_INC=${{targets.destdir}}/usr/local/include/luajit-2.1
      
      echo "::::::::::::::::::::::::::::::::::::::"
      echo ":::: luajit2-{{ .LUAJIT_VERSION }} ::::"
      echo "::::::::::::::::::::::::::::::::::::::"
      
      make CCDEBUG=-g

  - uses: autoconf/make-install
