package:
  name: mimalloc
  version: {{ .MIMALOC_VERSION }}
  epoch: 0
  description: "mimalloc is a compact general purpose allocator with excellent performance."
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      license: MIT license
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
    packages:
      - alpine-baselayout-data
      - busybox
      - build-base
      - ssl_client
      - ca-certificates-bundle
      - cmake

  accounts:
    groups:
      - groupname: www-data
        gid: 10000
    users:
      - username: www-data
        uid: 10000

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/microsoft/mimalloc/archive/refs/tags/v{{ .MIMALOC_VERSION }}.tar.gz
      expected-sha256: {{ .MIMALOC_VERSION_SHA }}
      strip-components: 1
  - name: 'Configure MIMALOC'
    with:
      MIMALOC_VERSION: {{ .MIMALOC_VERSION }}
    runs: |
      ls -lah
      cmake .
  - uses: autoconf/make
  - uses: autoconf/make-install
