package:
  name: modsecurity
  version: {{ .MODSECURITY_LIB_VERSION }}
  epoch: 0
  description: "ModSecurity is an open source, cross platform web application firewall (WAF) engine"
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      license: Apache-2.0 license
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
      - '@local /work/packages'

    packages:
      - alpine-baselayout-data
      - busybox
      - build-base
      - ssl_client
      - ca-certificates-bundle
      - git
      - cmake
      - autoconf
      - automake
      - pkgconf
      - make
      - automake
      - libtool
      - curl
      - curl-dev
      - libxml2
      - pcre
      - pcre-dev
      - linux-headers
      - luajit@local
  accounts:
    groups:
      - groupname: www-data
        gid: 10000
    users:
      - username: www-data
        uid: 10000

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/SpiderLabs/ModSecurity
      branch: {{ .MODSECURITY_LIB_VERSION }}
  - name: 'Configure MODSECURITY'
    with:
      MODSECURITY_LIB_VERSION: {{ .MODSECURITY_LIB_VERSION }}
    runs: |
      set -o errexit
      set -o nounset
      set -o pipefail
      # build modsecurity library
      
      echo "::::::::::::::::::::::::::::::::::::::"
      echo ":::: modsecurity {{ .MODSECURITY_LIB_VERSION }} ::::"
      echo "::::::::::::::::::::::::::::::::::::::"
      
      export LUAJIT_LIB=/usr/local/lib
      export LUA_LIB_DIR="$LUAJIT_LIB/lua"
      export LUAJIT_INC=/usr/local/include/luajit-2.1

      ls -lah
      git submodule init
      git submodule update
      
      sh build.sh
      
      # https://github.com/SpiderLabs/ModSecurity/issues/1909#issuecomment-465926762
      sed -i '115i LUA_CFLAGS="${LUA_CFLAGS} -DWITH_LUA_JIT_2_1"' build/lua.m4
      sed -i '117i AC_SUBST(LUA_CFLAGS)' build/lua.m4
      ./configure \
      --disable-doxygen-doc \
      --disable-doxygen-html \
      --disable-examples

  - uses: autoconf/make
  - uses: autoconf/make-install
