package:
  name: msgpack-cpp
  version: {{ .MSGPACK_VERSION }}
  epoch: 0
  description: "msgpack for C/C++."
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      license: Boost Software License - Version 1.0
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
      -
    packages:
      - alpine-baselayout-data
      - busybox
      - build-base
      - ssl_client
      - ca-certificates-bundle
      - cmake

  accounts:
    groups:
      - groupname: www-data
        gid: 10000
    users:
      - username: www-data
        uid: 10000

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/msgpack/msgpack-c/archive/cpp-{{ .MSGPACK_VERSION }}.tar.gz
      expected-sha256: {{ .MSGPACK_VERSION_SHA }}
      strip-components: 1
  - name: 'Configure MSGPACK'
    with:
      YAML_CPP_VERSION: {{ .YAML_CPP_VERSION }}
    runs: |
      # build msgpack lib
      echo "::::::::::::::::::::::::::::::::::::::"
      echo ":::: msgpack-c-cpp-{{ .MSGPACK_VERSION }} ::::"
      echo "::::::::::::::::::::::::::::::::::::::"
      
      cmake -DCMAKE_BUILD_TYPE=Release \
      -DBUILD_SHARED_LIBS=OFF \
      -DMSGPACK_BUILD_EXAMPLES=OFF \
      -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=true .

  - uses: autoconf/make
  - uses: autoconf/make-install
