package:
  name: opentracing
  version: {{ .OPENTRACING_CPP_VERSION }}
  epoch: 0
  description: "C++ implementation of the OpenTracing API http://opentracing.io"
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      license: Apache-2.0 license
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
    packages:
      - alpine-baselayout-data
      - busybox
      - build-base
      - ssl_client
      - ca-certificates-bundle
      - cmake

  accounts:
    groups:
      - groupname: www-data
        gid: 10000
    users:
      - username: www-data
        uid: 10000

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/opentracing/opentracing-cpp/archive/{{ .OPENTRACING_CPP_VERSION }}.tar.gz
      expected-sha256: {{ .OPENTRACING_CPP_VERSION_SHA }}
      strip-components: 1
  - name: 'Configure OPENTRACING CPP'
    with:
      OPENTRACING_CPP_VERSION: {{ .OPENTRACING_CPP_VERSION }}
    runs: |
      
      cmake -DCMAKE_BUILD_TYPE=Release \
      -DBUILD_TESTING=OFF \
      -DBUILD_SHARED_LIBS=OFF \
      -DBUILD_MOCKTRACER=OFF \
      -DBUILD_STATIC_LIBS=ON \
      -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=true \
      .
  - uses: autoconf/make
  - uses: autoconf/make-install
