package:
  name: zipkin-cpp
  version: {{ .ZIPKIN_CPP_VERSION }}
  epoch: 0
  description: "OpenTracing implementation for Zipkin in C++."
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      license: Apache-2.0 license
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
      - '@local /work/packages'
    packages:
      - alpine-baselayout-data
      - busybox
      - build-base
      - ssl_client
      - ca-certificates-bundle
      - cmake
      - curl
      - curl-dev
      - opentracing@local

  accounts:
    groups:
      - groupname: www-data
        gid: 10000
    users:
      - username: www-data
        uid: 10000

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/rnburn/zipkin-cpp-opentracing/archive/{{ .ZIPKIN_CPP_VERSION }}.tar.gz
      expected-sha256: {{ .ZIPKIN_CPP_VERSION_SHA }}
      strip-components: 1
  - name: 'Configure ZIPKIN CPP VERSION'
    with:
      OPENTRACING_CPP_VERSION: {{ .ZIPKIN_CPP_VERSION }}
    runs: |
      echo "::::::::::::::::::::::::::::::::::::::"
      echo ":::: zipkin-cpp-opentracing-{{ .ZIPKIN_CPP_VERSION }} ::::"
      echo "::::::::::::::::::::::::::::::::::::::"

      cat <<EOF > export.map
      {
        global:
          OpenTracingMakeTracerFactory;
          local: *;
      };
      EOF
      
      cmake -DCMAKE_BUILD_TYPE=Release \
      -DBUILD_SHARED_LIBS=OFF \
      -DBUILD_PLUGIN=ON \
      -DBUILD_TESTING=OFF \
      -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=true .

  - uses: autoconf/make
  - uses: autoconf/make-install
