apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  ports:
  - name: http
    hostPort: 80
    targetPort: 80
    protocol: TCP
  - name: https
    hostPort: 443
    targetPort: 443
    protocol: TCP
  selector:
    app: ingress-nginx
