controller:
  image:
    repository: ingress-controller/controller
    tag: 1.0.0-dev
    digest: null
  autoscaling:
    enabled: true
    behavior:
      scaleDown:
        stabilizationWindowSeconds: 300
        policies:
        - type: Pods
          value: 1
          periodSeconds: 180
  admissionWebhooks:
    enabled: false
  service:
    type: ClusterIP
