controller:
  image:
    repository: ingress-controller/controller
    tag: 1.0.0-dev
    digest: null
  service:
    type: ClusterIP
  admissionWebhooks:
    enabled: true
    extraEnvs:
      - name: FOO
        value: foo
      - name: TEST
        value: test
    patch:
      enabled: true
