# Left blank to test default values
controller:
  kind: StatefulSet
  volumeClaimTemplates:
  - metadata:
      name: cache
    spec:
      storageClassName: manual
      hostPath: "/mnt/nginx-cache"
      accessModes:
      - ReadWriteOnce
      capacity:
        storage: 1Gi
  extraVolumeMounts:
  - name: cache
    mountPath: /cache
  image:
    repository: ingress-controller/controller
    tag: 1.0.0-dev
    digest: null
  service:
    type: ClusterIP
