# Left blank to test default values
controller:
  kind: StatefulSet
  podManagementPolicy: Parallel
  image:
    repository: ingress-controller/controller
    tag: 1.0.0-dev
    digest: null
  service:
    type: ClusterIP
