name: Adds all issues

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    permissions:
      repository-projects: write
      issues: write
    steps:
      - uses: peter-evans/create-or-update-project-card@2384ab088fea261837be59baa1ba295694c4e74a
        with:
          project-location: organization
          project-number: 104
          issue-number: ${{ github.event.number }}
          column-name: "Needs Triage"
          token: ${{ secrets.PROJECT_WRITER }}
