name: test-malicious-protection
on:
  pull_request:
    types: [ opened, synchronize, labeled ]
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: rogue command
        run: |
          echo "If you see this, that's bad"
